import store from './Store'
import { setCity, deleteCity } from './reducers/cityList'
import { fixActiveCity } from './reducers/activeCity'
import { GetCityList } from './selectors/CityList'
import {
    GetForecastList,
    GetHourlyList,
    GetTempHigh,
    GetTempLow,
    GetDescription,
    GetTempCurrent,
    GetNameCity,
    GetIpNameCity,
    GetUvIndex,
    GetSunrise,
    GetTime,
    GetHumidity,
    GetVisibility,
    GetActiveCity,
    GetNameUvi,
    GetImgUvi,
    GetDescriptionUvi,
    GetNameSunrise,
    GetNameHumidity,
    GetNameWind,
    GetNameVisibility,
    GetLevelUvi,
    GetImgSunrise,
    GetImgWind,
    GetImgCompass,
    GetNameFeelsLike,
    GetImgFeelsLike,
    GetSignFeelsLike,
    GetDescriptionFeelsLike,
    GetImgVisibility,
    GetDescriptionVisibility,
    GetSignVisibility,
    GetImgHumidity,
    GetDescriptionHumidity,
    GetSignHumidity,
} from './selectors/activeCity'

export {
    store,
    setCity,
    deleteCity,
    GetCityList,
    GetForecastList,
    GetHourlyList,
    GetTempHigh,
    GetTempLow,
    GetDescription,
    GetTempCurrent,
    GetNameCity,
    GetIpNameCity,
    GetUvIndex,
    GetSunrise,
    GetTime,
    GetHumidity,
    GetVisibility,
    GetActiveCity,
    fixActiveCity,
    GetNameUvi,
    GetImgUvi,
    GetDescriptionUvi,
    GetNameSunrise,
    GetNameHumidity,
    GetNameWind,
    GetNameVisibility,
    GetLevelUvi,
    GetImgSunrise,
    GetImgWind,
    GetImgCompass,
    GetNameFeelsLike,
    GetImgFeelsLike,
    GetSignFeelsLike,
    GetDescriptionFeelsLike,
    GetImgVisibility,
    GetDescriptionVisibility,
    GetSignVisibility,
    GetImgHumidity,
    GetDescriptionHumidity,
    GetSignHumidity,
}
